config/routes.rb
IbhartiRadio::Application.routes.draw do
  
  ActiveAdmin.routes(self)

    devise_for :admin_users, ActiveAdmin::Devise.config
    devise_for :users, 
        :controllers => { 
          :sessions           => 'devise/sessions', 
          :registrations      => 'devise/registrations', 
          :confirmations      => 'devise/confirmations', 
          :passwords          => 'devise/passwords',
          :omniauth_callbacks => 'users/omniauth_callbacks'
        },
        :path => '',
        :path_names => {:sign_in => 'users/sign_in', :sign_out => 'users/sign_out', :sign_up => 'users/sign_up'}

    namespace :api do
      devise_for :users, :controllers => { 
          :sessions           => 'api/sessions', 
          :registrations      => 'api/registrations', 
          :confirmations      => 'api/confirmations' 
        }  
    end  

 
  resources :users  

  resources :colleges

  resources :cities

  resources :song_uploads

  resources :songs

  resources :tags

  resources :languages

  resources :categories

  match 'index' => 'main#index'
  match 'live_station' => 'main#live_stationhahahahahahah'
  match 'songs_by_lang' => 'main#songs_by_lang'
  match 'songs_by_cat' => 'main#songs_by_cat'

  root :to => "main#index" 

end

app/models/song_upload.rb
class SongUpload < ActiveRecord::Base
  resourcify
  belongs_to :song
  attr_accessible :file, :song_id

  mount_uploader :file, SongUploader
end

app/controllers/song_uploads_controller.rb
class SongUploadsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /song_uploads
  # GET /song_uploads.json
  def index
    @song_uploads = SongUpload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @song_uploads }
    end
  end

  # GET /song_uploads/1
  # GET /song_uploads/1.json
  def show
    @song_upload = SongUpload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song_upload }
    end
  end

  # GET /song_uploads/new
  # GET /song_uploads/new.json
  def new
    @song_upload = SongUpload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song_upload }
    end
  end

  # GET /song_uploads/1/edit
  def edit
    @song_upload = SongUpload.find(params[:id])
  end

  # POST /song_uploads
  # POST /song_uploads.json
  def create
    @song_upload = SongUpload.new(params[:song_upload])

    respond_to do |format|
      if @song_upload.save
        format.html { redirect_to @song_upload, notice: 'Song upload was successfully created.' }
        format.json { render json: @song_upload, status: :created, location: @song_upload }
      else
        format.html { render action: "new" }
        format.json { render json: @song_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /song_uploads/1
  # PUT /song_uploads/1.json
  def update
    @song_upload = SongUpload.find(params[:id])

    respond_to do |format|
      if @song_upload.update_attributes(params[:song_upload])
        format.html { redirect_to @song_upload, notice: 'Song upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /song_uploads/1
  # DELETE /song_uploads/1.json
  def destroy
    @song_upload = SongUpload.find(params[:id])
    @song_upload.destroy

    respond_to do |format|
      format.html { redirect_to song_uploads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/song_uploads_helper.rb
module SongUploadsHelper
end

app/views/song_uploads/_form.html.erb
<%= form_for @song_upload, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :file, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :file, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :song_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :song_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                song_uploads_path, :class => 'btn' %>
  </div>
<% end %>

app/views/song_uploads/edit.html.erb
<%- model_class = SongUpload -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/song_uploads/index.html.erb
<%- model_class = SongUpload -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:file) %></th>
      <th><%= model_class.human_attribute_name(:song_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @song_uploads.each do |song_upload| %>
      <tr>
        <td><%= link_to song_upload.id, song_upload_path(song_upload) %></td>
        <td><%= song_upload.file %></td>
        <td><%= song_upload.song_id %></td>
        <td><%=l song_upload.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_song_upload_path(song_upload), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      song_upload_path(song_upload),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_song_upload_path,
            :class => 'btn btn-primary' %>

app/views/song_uploads/new.html.erb
<%- model_class = SongUpload -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/song_uploads/show.html.erb
<%- model_class = SongUpload -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:file) %>:</strong></dt>
  <dd><%= @song_upload.file %></dd>
  <dt><strong><%= model_class.human_attribute_name(:song_id) %>:</strong></dt>
  <dd><%= @song_upload.song_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              song_uploads_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_song_upload_path(@song_upload), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              song_upload_path(@song_upload),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>