config/routes.rb
IbhartiRadio::Application.routes.draw do
  
  ActiveAdmin.routes(self)

    devise_for :admin_users, ActiveAdmin::Devise.config
    devise_for :users, 
        :controllers => { 
          :sessions           => 'devise/sessions', 
          :registrations      => 'devise/registrations', 
          :confirmations      => 'devise/confirmations', 
          :passwords          => 'devise/passwords',
          :omniauth_callbacks => 'users/omniauth_callbacks'
        },
        :path => '',
        :path_names => {:sign_in => 'users/sign_in', :sign_out => 'users/sign_out', :sign_up => 'users/sign_up'}

    namespace :api do
      devise_for :users, :controllers => { 
          :sessions           => 'api/sessions', 
          :registrations      => 'api/registrations', 
          :confirmations      => 'api/confirmations' 
        }  
    end  

 
  resources :users  

  resources :colleges

  resources :cities

  resources :song_uploads

  resources :songs

  resources :tags

  resources :languages

  resources :categories

  match 'index' => 'main#index'
  match 'live_station' => 'main#live_stationhahahahahahah'
  match 'songs_by_lang' => 'main#songs_by_lang'
  match 'songs_by_cat' => 'main#songs_by_cat'

  root :to => "main#index" 

end

app/models/college.rb
class College < ActiveRecord::Base
  resourcify
  belongs_to :city
  has_many   :songs
  attr_accessible :name, :url, :city_id
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colleges }
    end
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
    @college = College.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @college }
    end
  end

  # GET /colleges/new
  # GET /colleges/new.json
  def new
    @cities = City.order 'name'
    @college = College.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @college }
    end
  end

  # GET /colleges/1/edit
  def edit
    @cities = City.order 'name'
    @college = College.find(params[:id])
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(params[:college])

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render json: @college, status: :created, location: @college }
      else
        format.html { render action: "new" }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colleges/1
  # PUT /colleges/1.json
  def update
    @college = College.find(params[:id])

    respond_to do |format|
      if @college.update_attributes(params[:college])
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college = College.find(params[:id])
    @college.destroy

    respond_to do |format|
      format.html { redirect_to colleges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= form_for @college, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city_id, :class => 'control-label' %>
    <div class="controls">
      <% if @cities.present? %>
        <%= f.collection_select :city_id, @cities, :id, :name, {:include_blank => "Select City"}, :class => 'number_field' %>
      <% else %>
        <input class="text_field", placeholder="No Cities found!", readonly/>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                colleges_path, :class => 'btn' %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<%- model_class = College -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/colleges/index.html.erb
<%- model_class = College -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:city_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= link_to college.id, college_path(college) %></td>
        <td><%= college.name %></td>
        <td><%= college.city.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_college_path(college), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      college_path(college),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_college_path,
            :class => 'btn btn-primary' %>

app/views/colleges/new.html.erb
<%- model_class = College -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/colleges/show.html.erb
<%- model_class = College -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @college.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city_id) %>:</strong></dt>
  <dd><%= @college.city_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              colleges_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_college_path(@college), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              college_path(@college),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>